# ------ root_path/dataset_name ------
root_path: 'C:\Users\Admin\Desktop\CLIP\$DATA' # ensure cfg['root_path'] is correctly set to the root directory of the dataset

# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparameters ------
search_hp: True

search_scale: [7, 3]
search_step: [200, 20]

init_gamma: 1
init_omega: 1.1
init_alpha: 1.17

# ------ Basic Config ------
dataset: 'dataset'
k: 16
backbone: 'RN50'
method: 'I2I'

lr: 0.001
train_epoch: 20